### PR TITLE
Don't merge empty Rubocop configurations

### LINKED ISSUE #983: Empty .rubocop_todo.yml crashes houndci
#### Description
If a rubocop config file included with ```inherit_from``` contains no entries except comments, houndci crashes with
> Error parsing config file: .rubocop.yml. Click "details" for assistance."

#### Steps to reproduce
1. Create a new .rubocop.yml config file and include it from .hound.yml
2. Use rubocop to generate .rubocop_todo.yml by running ```rubocop --auto-gen-config``` and add ```inherit_from .rubocop_todo.yml``` to .rubocop.yml ([link to sample commit](https://github.com/sdellenb/hound-test/commit/dd76a7fa68d7fea0142568211d97d6b4bd80bfd0))
3. Fix remaining offenses bit by bit and run ```rubocop --auto-gen-config``` before commit to get an updated .rubocop_todo.yml.
4. Once all offenses are fixed, .rubocop_todo.yml will only contain the generated comment header

#### Result
* houndci crashes with  
> Error parsing config file: .rubocop.yml. Click "details" for assistance."

#### Expected Result
* houndci should gracefully skip empty files while merging configs, since in this particular case the file is auto-generated.
* rubocop has no problem with the included file being empty

#### Sample link
I've set up a pull request where the issue occurs in the last commit: https://github.com/sdellenb/hound-test/pull/3

### PR DESCRIPTION
**Pull request by teoljungberg**
This is a behavior Rubocop has, Hound should not be any different.

Changes:

- Refactor: Move `ensure_correct_type` to `Config::MY_CONFIG#content`.
  The `#parse` method should not do more than just parsing.

Resolves #983

### CODE REVIEW

File: spec/models/config/ruby_spec.rb [hunk 1]
```diff
@@ -62,6 +62,28 @@
...
     end
+
+    context "with an empty `inherit_from`" do
+      it "works" do
+        rubocop = <<-EOS.strip_heredoc
+          inherit_from: config/base.yml
+          Style/Encoding:
+            Enabled: true
+        EOS
+        base = <<-EOS.strip_heredoc
```
Comment (arunagw) [inline spec/models/config/ruby_spec.rb]: Can we call this file `empty_ rubocop` ? `base` a bit confusing.

**Comment by arunagw** [comment]
One small comment otherwise looks fine to me.

File: spec/models/config/ruby_spec.rb (hunk 1 above)
Comment (teoljungberg) [inline spec/models/config/ruby_spec.rb]: Agreed, fixed and force pushed.
